### ISSUE TITLE
JavaScript vs TypeScript issues.

### ISSUE THREAD

**Issue by ccoddington** [aws-samples/amazon-textract-response-parser#43]
This code works with JavaScript but does not work with TypeScript:

![image](https://user-images.githubusercontent.com/7330081/141852024-6a965710-ff05-43bb-aba8-c35ed8fe150c.png)

When inspecting my combined.json file I see that it has the expected contents:

![image](https://user-images.githubusercontent.com/7330081/141852363-6e8a3b17-0ecc-4fbc-9539-0e5dd2063e9f.png)

TypeScript (run from an AWS Lambda) is throwing this error:

![image](https://user-images.githubusercontent.com/7330081/141853003-d926b43a-c8d5-439a-a640-b89e59dce8ec.png)

**Comment by dobeerman** [comment]
I faced the same issue. Does anyone solved it? :thinking:

**Comment by athewsey** [comment]
Hi both & thanks for raising this,

I've managed to reproduce it when using SAM's (beta) TypeScript Lambda function builder, but am not seeing it when writing TypeScript and just using e.g. `tsc` to build it into JS.

I found that changing the Lambda's `tsconfig.json` from SAM's default `"module": "es2015",` to target `"module": "umd"` seemed like it might fix the issue... But not certain yet whether there might be a TRP-side fix we could/should make instead.

Would love to hear:

1. Whether this tsconfig fix solves the issue for you? and
2. A bit more info about exactly how affected folks are using TypeScript: Is it through SAM as mentioned? Something else? What's in your `tsconfig.json`?)

**Comment by dobeerman** [comment]
I solved it with 

```ts
import { Field, TextractDocument } from 'amazon-textract-response-parser/dist/cjs'
```

**Comment by athewsey** [comment]
Thanks

After a closer look, I think we should be able to improve this by aligning the standard entry point to CJS instead of UMD (so `/dist/cjs` not needed). It'd be consistent with what the AWS SDK for JS itself does, and we can offer modern ES6/esnext bundling as an alternative rather than UMD (also like they do), for any toolchains that want it.

I've rolled it in to the proposed next TRP.js version and done some various usage testing as mentioned in the linked PR.

@dobeerman or others if you have time to try out [v0.2.0-alpha.2](https://www.npmjs.com/package/amazon-textract-response-parser/v/0.2.0-alpha.2) from NPM, it'd be great to know whether it works better for you?

**Comment by athewsey** [comment]
Closing as [v0.2.0](https://www.npmjs.com/package/amazon-textract-response-parser/v/0.2.0) is now launched already and believe it should fix.
