### ISSUE TITLE
Table.rows_without_header function adds duplicate non_header_rows - the call is 1-level too deep

### ISSUE THREAD

**Issue by cleung11** [aws-samples/amazon-textract-response-parser#55]
The function checks if a row is not a header and appends the row within the cell for loop (adds a row for each cell). It should be moved one level out into the row for loop instead:
https://github.com/aws-samples/amazon-textract-response-parser/blob/master/src-python/trp/__init__.py#L431

Original:
```
    @property
    def rows_without_header(self) -> List[Row]:
        non_header_rows: List[Row] = list()
        for row in self.rows:
            header = False
            for cell in row.cells:
                for entity_type in cell.entityTypes:
                    if entity_type == ENTITY_TYPE_COLUMN_HEADER:
                        header = True
                if not header:
                    non_header_rows.append(row)
        return non_header_rows
```
New:
```
    @property
    def rows_without_header(self) -> List[Row]:
        non_header_rows: List[Row] = list()
        for row in self.rows:
            header = False
            for cell in row.cells:
                for entity_type in cell.entityTypes:
                    if entity_type == ENTITY_TYPE_COLUMN_HEADER:
                        header = True
            if not header: # moved this left one tab
                non_header_rows.append(row) # moved this left one tab
        return non_header_rows
```

**Comment by athewsey** [comment]
Hi, thank you for taking the time to raise this and propose a fix - and apologies for the slow response!

It looks like this issue was actually [fixed](https://github.com/aws-samples/amazon-textract-response-parser/blob/c49cca5053a4b053a6ff171fd0adeb31586d053f/src-python/trp/__init__.py#L521) in 160d1353b443921db2f28acbdb3d41bae64a5acf, which was merged in #57 (2022-05-06) and I *believe* released in PyPI version [0.1.30](https://pypi.org/project/amazon-textract-response-parser/0.1.30/) (maybe 0.1.31)

Therefore closing this issue as completed. If anybody's still seeing this behaviour in newer versions, please re-open.
